#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $2 | tail -n +2 | while read -r line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo "$line" | awk '{print $1}')
  CPU=$(echo "$line" | awk '{print $2}')
  MEMORY=$(echo "$line" | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  printf "%-20s %-20s %-20s %-20s %-20s\n" "RESOURCE_TYPE" "NAMESPACE" "NAME" "CPU" "MEMORY"
  printf "%-20s %-20s %-20s %-20s %-20s\n" "$RESOURCE_TYPE" "$2" "$NAME" "$CPU" "$MEMORY"
done